### ISSUE TITLE
There is a warning message related to allocation

### ISSUE THREAD

**Issue by thuang6** [intel/workload-collocation-agent#163]
WARNING  {MainThread} [wca.storage] failed to convert metrics intoprometheus exposition format; error: "Used wrong label name org.apache.aurora.tier in metric allocation_cpu_quota." - skipping

**Comment by ppalucki** [comment]
There was an bug introduced by me, when we tried to update the changes labels for kubernetes - unluckily is also broke the Mesos labels sanitizing mechanism. We missed that, because `LogStorage` class was silently ignoring messages that cannot be encoded - it is fixed now:
- it will both stop the program with serious error 
- and now all metrics are properly encoded

fixed in #165 in both master and 1.0.x
